---

name: Make Repository

on:
  push:
    branches:
      - main
      - debug
      - feature/**
  schedule:
    - cron: "21 4 * * 0"

permissions:
  # Allow creating GitHub release
  contents: write

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Makepkg Build and Check
      id: makepkg
      uses: Pinghigh/pkgbuild-action@v5
      with:
        makepkgArgs: "--skippgpcheck --noconfirm"

    - name: Print Package Files
      run: |
        echo "package=${{ steps.makepkg.outputs.pkgfile0 }}" >> $GITHUB_ENV
        echo "Successfully created the following package archive"
        printf '%s\n' "$package"

    # Uncomment to upload the package as an artifact
    - name: Upload Package Archive
      id: upload_package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.makepkg.outputs.pkgfile0 }}
        path: ${{ steps.makepkg.outputs.pkgfile0 }}

    - name: Release
      uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ steps.makepkg.outputs.pkgfile0 }}
        token: ${{ github.token }}

    # - name: upload artifact
    #   uses: actions/upload-release-asset@v3
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ""
    #     asset_path: ${{ steps.makepkg.outputs.pkgfile0 }}
    #     asset_name: ${{ steps.makepkg.outputs.pkgfile0 }}
    #     asset_content_type: application/zstd
